### PR TITLE
Fixing monomials_from_data.

### PR DESCRIPTION
**Pull request by 1ozturkbe**

### CODE REVIEW

**Comment by 1ozturkbe** [comment]
failing due to this...
```python 
ERROR: Package 'setuptools' requires a different Python: 2.7.16 not in '>=3.5'
Build step 'Conditional step (single)' marked build as failure
```
Arg.

**Comment by bqpd** [comment]
huh, why is this python3 specific?

**Comment by 1ozturkbe** [comment]
No freaking idea. I guess 'setuptools' dropped support for Python2?

**Comment by 1ozturkbe** [comment]
test this please

**Comment by 1ozturkbe** [comment]
It seems that ``` pip install --upgrade matplotlib``` triggers setuptools, which requires python version >=3.5. Don't understand why other repos don't have the same problem. Do they not install matplotlib?

**Comment by bqpd** [comment]
that line seems to works on the gpkit tests?

**Comment by 1ozturkbe** [comment]
I'm going to merge this, since this is a python2 vs. 3 issue rather than a PR issue.

**Pull request merged**
