### PR TITLE
center uncertainty region around original value

### PR DESCRIPTION
**Pull request by bqpd**
this shouldn't be merged until the recentering is done during the robust-model's creation as opposed to in this adhoc fashion.

### CODE REVIEW

**Comment by bqpd** [comment]
image

**Comment by alisaab** [comment]
I am afraid that this will not solve the problem. Now the robust problem is being solved for a different interval than the one specified by the user. the most convenient (not user friendly though) is to specify the uncertainty in the log space.

**Comment by alisaab** [comment]
or we might solve the robust problem with the original values, and then change the value of the uncertain parameters in the original model to the centered values.

**Comment by bqpd** [comment]
I think this is expressing user's intent much better than what you're proposing, so I think it does solve the problem...

**Comment by bqpd** [comment]
It was agreed in person today that @alisaab had the right of it, but that we should potentially change how uncertain parameters are declared!

**Pull request closed without merging**
