### PR TITLE
Plots for robustSPpaper + fix diffs. 

### PR DESCRIPTION
**Pull request by 1ozturkbe**

### CODE REVIEW

**Comment by 1ozturkbe** [comment]
@bqpd I checked the diffs for robust and they seem pretty significant. I don't think we can attribute to changes in gpkit. I'm going to check the former commits to see what might have changed.

**Comment by 1ozturkbe** [comment]
It seems like mosek now finds better optima for all of the problems... weird. But looks nothing out of the ordinary, and the other pushes look fine too. I guess I'll just update the diffs.

**Comment by 1ozturkbe** [comment]
Aight, will change to a pickle and diff when I have time.

**Comment by bqpd** [comment]
this is maybe because of the switch to pccpsolve?

**Comment by 1ozturkbe** [comment]
test this please

**Pull request merged**
